  GNU nano 6.2                                                      /etc/netplan/00-installer-config.yaml *                                                              
# This is the network config written by 'subiquity'
network:
  ethernets:
    enp1s0:
      dhcp4: false
      addresses: [10.13.0.5/22]
      routes:
      - to : default
        via: 10.13.0.1
      nameservers:
        addresses: [8.8.8.8]
    enp7s0:
      dhcp4: false
      addresses: [10.14.0.5/22]
      routes: 
      - to : default
        via: 10.14.0.1
      nameservers:
        addresses: [8.8.8.8]
    enp8s0:
      dhcp4: false
      addresses: [10.15.0.5/22]
      routes: 
      - to : default
        via: 10.15.0.1
      nameservers:
        addresses: [8.8.8.8]



  version: 2


