network:
  version: 2
  renderer: networkd

  ethernets:
    eno12399np0:
      dhcp4: false 
      dhcp6: false 
    eno8303:
      dhcp4: false
    eno12409np1:
      dhcp4: false
    eno8403:
      dhcp4: false
    

  bridges:
    br0:
      interfaces: [eno12399np0]
      addresses: [10.14.0.3/22]
      # gateway4 is deprecated, use routes instead
      routes:
      - to: default
        via: 10.14.0.1
        metric: 100
        on-link: true
      mtu: 1500
      nameservers:
        addresses: [8.8.8.8]
      parameters:
        stp: true
        forward-delay: 4
      dhcp4: no
      dhcp6: no

    br1:
      interfaces: [eno12409np1]
      addresses: [10.15.0.3/22]
      # gateway4 is deprecated, use routes instead
      routes:
      - to: default
        via: 10.15.0.1
        metric: 100
        on-link: true
      mtu: 1500
      nameservers:
        addresses: [8.8.8.8]
      parameters:
        stp: true
        forward-delay: 4
      dhcp4: no
      dhcp6: no

    br-realip:
      interfaces: [eno8303]
      addresses: [103.108.62.219/29]
      # gateway4 is deprecated, use routes instead
      routes:
      - to: default
        via: 103.108.62.217
        metric: 100
        on-link: true
      mtu: 1500
      nameservers:
        addresses: [8.8.8.8]
      parameters:
        stp: true
        forward-delay: 4
      dhcp4: no
      dhcp6: no


    br13:
      interfaces: [eno8403]
      addresses: [10.13.0.3/22]
      # gateway4 is deprecated, use routes instead
      routes:
      - to: default
        via: 10.13.0.1
        metric: 100
        on-link: true
      mtu: 1500
      nameservers:
        addresses: [8.8.8.8]
      parameters:
        stp: true
        forward-delay: 4
      dhcp4: no
      dhcp6: no
